# Generated by Django 5.2.3 on 2025-08-28 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamNarration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_text', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=32, null=True)),
                ('emotion', models.CharField(blank=True, max_length=128, null=True)),
                ('analysis_json', models.JSONField(blank=True, null=True)),
                ('potential_condition', models.CharField(blank=True, max_length=128, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams_dreams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
